id: I70D33A01
legacy_id: P010325
ocr_import_info:
  bdrc_scan_id: W1CZ1213
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:53:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:00:15.765715+00:00'
last_modified: 2022-08-31 03:00:24.964244
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1213
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1213
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་མཆོག་ལུ་ནག་གཉིས་ཀྱི་ཟིན་བྲིས།
  author: ཉག་རེ་པྲ་བྷ།
statistics:
  ocr_word_mean_confidence_index: 0.5168056378421348
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1CZ2063:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2063
      total_pages: 34
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2063.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5168056378421348
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
